# Generated by Django 5.1.1 on 2024-10-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код экзамина')),
                ('exam_name', models.CharField(max_length=128, verbose_name='Название экзамена')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код тарифа')),
                ('tariff_name', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('price', models.FloatField(verbose_name='Цена тарифа')),
                ('tariff_info', models.TextField(verbose_name='Информация о тарифе')),
            ],
        ),
        migrations.CreateModel(
            name='PointsOfTask',
            fields=[
                ('code_of_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код типа')),
                ('points', models.IntegerField(verbose_name='Баллы')),
                ('fk_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код номера')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('image_path', models.CharField(max_length=128, verbose_name='Путь до изображения')),
                ('correct_answer', models.CharField(max_length=128, verbose_name='Правильный ответ')),
                ('fk_code_of_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_of_number', to='main.exam')),
                ('fk_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_task', to='main.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код учителя')),
                ('hash_login', models.CharField(max_length=128, verbose_name='Хэш логина')),
                ('hash_password', models.CharField(max_length=128, verbose_name='Хэш пароля')),
                ('hash_email', models.CharField(max_length=128, verbose_name='Хэш почты')),
                ('fk_tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersToExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_teacher', to='main.exam')),
                ('fk_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_e', to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersToStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_t', to='main.student')),
                ('fk_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_s', to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код варианта')),
                ('creator_id', models.CharField(max_length=10, verbose_name='Код создателя')),
                ('visibility', models.BooleanField(verbose_name='Доступность')),
                ('time_limit', models.TimeField(verbose_name='Временное ограничение')),
                ('fk_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_v', to='main.exam')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersVariantStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead_line', models.DateTimeField(verbose_name='Дедлайн')),
                ('fk_student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_t_v', to='main.student')),
                ('fk_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_v_s', to='main.teacher')),
                ('fk_variant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_t_s', to='main.variant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantToTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taskr_v', to='main.task')),
                ('fk_variant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_task', to='main.variant')),
            ],
        ),
    ]
