# Generated by Django 5.1.1 on 2024-11-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exam_tariff_pointsoftask_task_teacher_teacherstoexam_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointsOfTask',
            new_name='TypeOfTask',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='fk_code_of_number',
            new_name='fk_code_of_type',
        ),
        migrations.RenameField(
            model_name='typeoftask',
            old_name='code_of_number',
            new_name='code_of_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hash_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hash_login',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hash_email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hash_login',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='em', max_length=128, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='nam', max_length=32, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default='sur', max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator_id',
            field=models.ForeignKey(default=112211, on_delete=django.db.models.deletion.PROTECT, related_name='task_creator', to='main.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='file_path',
            field=models.CharField(default=113311, max_length=128, verbose_name='Путь до файла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='em', max_length=128, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='nam', max_length=32, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(default='sur', max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tariff_end_date',
            field=models.DateTimeField(default='em'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hash_password',
            field=models.CharField(max_length=32, verbose_name='Хэш пароля'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_creator', to='main.teacher'),
        ),
    ]
