# Generated by Django 5.1.1 on 2024-11-23 09:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_pointsoftask_typeoftask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator_id',
            field=models.ForeignKey(default='112211', on_delete=django.db.models.deletion.PROTECT, related_name='task_creator', to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file_path',
            field=models.CharField(default='113311', max_length=128, verbose_name='Путь до файла'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tariff_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 14, 37, 15, 442420)),
        ),
    ]
